### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by shuhei-fujita** [shuhei-fujita/playground-mysql#10]
※ システムの原理を深く理解するために、今回はORMを使わずに素のSQLを使ってCRUD操作を実装します

```bash
gh issue list
```

- [ ] #11  セキュリティの学習            less than a minute ago
- [ ] #9  様々な通信プロトコルの導入    less than a minute ago
- [ ] #8  APIのデプロイ               about 4 minutes ago
- [ ] #7  テストの実施                about 5 minutes ago
- [ ] #6  ロギングの導入              about 5 minutes ago
- [ ] #5  データベースとの統合        about 6 minutes ago
- [ ] #4  エラーハンドリングの実装    about 9 minutes ago
- [ ] #3  認証と認可の実装            about 10 minutes ago
- [x] #2 #16 HTTPリクエストの定義
